# Generated by Django 4.2.9 on 2024-01-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_remove_post_post_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_intro',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
