# Generated by Django 4.2.9 on 2024-01-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_category_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='visitor_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
