# Generated by Django 4.2.9 on 2024-01-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.BooleanField(default=False),
        ),
    ]
