# Generated by Django 4.2.9 on 2024-01-21 15:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='post_title', unique=True),
        ),
    ]
