# Generated by Django 4.2.9 on 2024-01-23 03:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='post_title', unique=True),
        ),
    ]
