# Generated by Django 4.2.9 on 2024-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
